version: '3.7'
services:
  anime-loads:
    build: .
    container_name: anime-loads
    volumes:
      - /mnt/user/appdata/anime-loads:/config
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
